version: '3.5'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile

  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - 8083:8080
      - 7077:7077
      - 6066:6066
    volumes:
      - .:/data
    environment:
      PORT: 3030

