version: '3.5'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile

  master:
    build:
      context: .
      dockerfile: Dockerfile.master
    ports:
      - 8083:8080
      - 7077:7077
      - 6066:6066
    volumes:
      - .:/data
    environment:
      PORT: 3030

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    volumes:
      - .:/data
    links:
      - master
    environment:
      PORT: 3030
      SPARK_MASTER: "spark://master:7077"

  python:
    image: python:3.7
    command: bash
    commmand: "cd /app && make pip-install"
    volumes:
      - ./app:/app

  submit:
    build:
      context: .
      dockerfile: Dockerfile.pysubmit
    volumes:
      - ./app/:/code
    links:
      - master
      - worker
    environment:
      PORT: 3030
      SPARK_MASTER: "spark://master:7077"
      BUILD_HOME: "/code/dist"
      SPARK_CODE: "jobs.zip main.py"
      SPARK_JOB: "wordcount"



