FROM pyspark_base

COPY worker.sh /

ENV SPARK_WORKER_WEBUI_PORT 8081
ENV SPARK_WORKER_LOG /app/spark/logs
ENV SPARK_MASTER "spark://spark-master:7077"


COPY worker.sh  /app/worker.sh

CMD ["/bin/bash", "/app/worker.sh"]
