FROM pyspark_base


ENV SPARK_MASTER_PORT 7077
ENV SPARK_MASTER_WEBUI_PORT 8080
ENV SPARK_MASTER_LOG /app/spark/logs

EXPOSE 8080 7077 6066

COPY master.sh /app/master.sh

CMD ["/bin/bash", "/app/master.sh"]
